// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SumberMas2015.SalesMarketing.InfrastructureData.Context;

namespace SumberMas2015.SalesMarketing.InfrastructureData.Migrations
{
    [DbContext(typeof(SalesMarketingContext))]
    [Migration("20211023113259_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.MasterBidangPekerjaanDB", b =>
                {
                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("MasterBidangPekerjaanDBGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NamaMasterBidangPekerjaan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TanggalInput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("TanggalInput")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("NoUrutId");

                    b.ToTable("MasterBidangPekerjaanDB");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.MasterBidangUsahaDB", b =>
                {
                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NamaMasterBidangUsaha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NamaMasterBidangUsahaGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TanggalInput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("TanggalInput")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("NoUrutId");

                    b.ToTable("MasterBidangUsahaDB");
                });
#pragma warning restore 612, 618
        }
    }
}
