// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SumberMas2015.SalesMarketing.InfrastructureData.Context;

namespace SumberMas2015.SalesMarketing.InfrastructureData.Migrations
{
    [DbContext(typeof(SalesMarketingContext))]
    [Migration("20211106105902_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.DataKonsumen", b =>
                {
                    b.Property<Guid>("DataKonsumenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgamaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("JenisKelaminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KodeBidangPekerjaan")
                        .HasColumnType("int");

                    b.Property<int>("KodeBidangUsaha")
                        .HasColumnType("int");

                    b.Property<string>("NamaBidangPekerjaan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaBidangUsaha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoKTP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("TanggalLahir")
                        .HasColumnType("datetime");

                    b.Property<string>("Terinput")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DataKonsumenId");

                    b.ToTable("DataKonsumen");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.DataPenjualan", b =>
                {
                    b.Property<Guid>("DataPenjualanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Batal")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<Guid>("DataKonsumenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DataSPKId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<Guid>("MasterKategoriPenjualanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MasterLeasingCabangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mediator")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("NoBuku")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("NoRegistrasiPenjualan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NoRegistrasiPenjualan");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("SalesUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SalesUserId");

                    b.Property<DateTime>("TanggalPenjualan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserNameInput")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("UserNameInput");

                    b.HasKey("DataPenjualanId");

                    b.ToTable("Penjualan");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.DataPenjualanDetail", b =>
                {
                    b.Property<Guid?>("DataPenjualanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BBN")
                        .HasColumnType("money")
                        .HasColumnName("BBN");

                    b.Property<string>("CheckDp")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("CheckDP");

                    b.Property<string>("CheckLapBulanan")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("CheckLapBulanan");

                    b.Property<Guid>("DataPenjualanDetailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DataPenjualanId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DendaWilayah")
                        .HasColumnType("money");

                    b.Property<decimal?>("DiskonKredit")
                        .HasColumnType("money");

                    b.Property<decimal?>("DiskonTunai")
                        .HasColumnType("money");

                    b.Property<decimal?>("HargaOTR")
                        .HasColumnType("money")
                        .HasColumnName("HargaOTR");

                    b.Property<decimal?>("JoinPromo1")
                        .HasColumnType("money");

                    b.Property<decimal?>("JoinPromo2")
                        .HasColumnType("money");

                    b.Property<decimal?>("Komisi")
                        .HasColumnType("money");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("OffTheRoad")
                        .HasColumnType("money")
                        .HasColumnName("OffTheRoad");

                    b.Property<decimal?>("Promosi")
                        .HasColumnType("money");

                    b.Property<decimal?>("SPF")
                        .HasColumnType("money")
                        .HasColumnName("SPF");

                    b.Property<decimal?>("SellOut")
                        .HasColumnType("money");

                    b.Property<Guid?>("StokUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Subsidi")
                        .HasColumnType("money");

                    b.Property<DateTime?>("TanggalCheckLapBulanan")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("UangMuka")
                        .HasColumnType("money");

                    b.Property<string>("UserCheckLapBulanan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UserCheckLapBulanan");

                    b.HasKey("DataPenjualanId");

                    b.HasIndex("DataPenjualanId1");

                    b.ToTable("PenjualanDetail");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.DataSPK", b =>
                {
                    b.Property<Guid>("DataSPKId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LokasiSpk")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NoRegistrasiSPK")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("StatusSPK")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TanggalInput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Tolak")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserNameInput")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DataSPKId");

                    b.ToTable("DataSPK");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.DataSPKKendaraan", b =>
                {
                    b.Property<Guid>("DataSPKKendaraanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DataSPKId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MasterBarangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NamaSTNK")
                        .HasMaxLength(35)
                        .IsUnicode(false)
                        .HasColumnType("varchar(35)");

                    b.Property<string>("NoKtpSTNK")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TahunPerakitan")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Warna")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.HasKey("DataSPKKendaraanId");

                    b.ToTable("DataSPKKendaraan");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.DataSPKKredit", b =>
                {
                    b.Property<Guid>("DataSPKKreditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BBN")
                        .HasColumnType("money");

                    b.Property<decimal?>("BiayaAdministrasiKredit")
                        .HasColumnType("money");

                    b.Property<decimal?>("BiayaAdministrasiTunai")
                        .HasColumnType("money");

                    b.Property<decimal?>("DPPriceList")
                        .HasColumnType("money");

                    b.Property<Guid>("DataSPKId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DendaWilayah")
                        .HasColumnType("money");

                    b.Property<decimal?>("DiskonDP")
                        .HasColumnType("money");

                    b.Property<decimal?>("DiskonTunai")
                        .HasColumnType("money");

                    b.Property<decimal?>("Komisi")
                        .HasColumnType("money");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("OffTheRoad")
                        .HasColumnType("money");

                    b.Property<decimal?>("Promosi")
                        .HasColumnType("money");

                    b.Property<decimal?>("UangTandaJadiKredit")
                        .HasColumnType("money");

                    b.Property<decimal?>("UangTandaJadiTunai")
                        .HasColumnType("money");

                    b.HasKey("DataSPKKreditId");

                    b.HasIndex("DataSPKId");

                    b.ToTable("DataSPKKredit");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.DataSPKLeasing", b =>
                {
                    b.Property<Guid>("DataSPKLeasingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Angsuran")
                        .HasColumnType("money");

                    b.Property<Guid>("DataSPKId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MasterKategoriBayaranId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MasterKategoriPenjualanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MasterLeasingCabangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mediator")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("NamaCmo")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<Guid>("NamaSales")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("TanggalSurvei")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Tenor")
                        .HasColumnType("int");

                    b.HasKey("DataSPKLeasingId");

                    b.HasIndex("DataSPKId");

                    b.HasIndex("MasterKategoriBayaranId");

                    b.HasIndex("MasterKategoriPenjualanId");

                    b.HasIndex("MasterLeasingCabangId");

                    b.ToTable("DataSPKLeasing");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.DataSPKSurvei", b =>
                {
                    b.Property<Guid>("DataSPKSurveiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DataSPKId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoKTPPemesan")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PekerjaanPemesan")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("DataSPKSurveiId");

                    b.HasIndex("DataSPKId");

                    b.ToTable("DataSPKSurvei");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.DataSalesMarketing", b =>
                {
                    b.Property<Guid>("DataSalesMarketingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NamaSales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("DataSalesMarketingId");

                    b.ToTable("DataSalesMarketing");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.EnumInEntity.Agama", b =>
                {
                    b.Property<Guid>("AgamaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgamaKeterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("AgamaId");

                    b.ToTable("Agama");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.EnumInEntity.JenisKelamin", b =>
                {
                    b.Property<Guid>("JenisKelaminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JenisKelaminKeterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("JenisKelaminId");

                    b.ToTable("JenisKelamin");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.MasterBarang", b =>
                {
                    b.Property<Guid>("MasterBarangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Bbn")
                        .HasColumnType("money");

                    b.Property<decimal?>("HargaOff")
                        .HasColumnType("money");

                    b.Property<string>("KapasitasMesin")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<int>("MasterBarangStatus")
                        .HasColumnType("int");

                    b.Property<string>("Merek")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NamaBarang")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomorMesin")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NomorRangka")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TahunPerakitan")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("TypeKendaraan")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MasterBarangId");

                    b.ToTable("MasterBarang");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.MasterBidangPekerjaanDB", b =>
                {
                    b.Property<Guid>("MasterBidangPekerjaanDBGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NamaMasterBidangPekerjaan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("TanggalInput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("TanggalInput")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("MasterBidangPekerjaanDBGuid");

                    b.ToTable("MasterBidangPekerjaanDB");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.MasterBidangUsahaDB", b =>
                {
                    b.Property<Guid>("MasterBidangUsahaGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NamaMasterBidangUsaha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("TanggalInput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("TanggalInput")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("MasterBidangUsahaGuid");

                    b.ToTable("MasterBidangUsahaDB");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.MasterKategoriBayaran", b =>
                {
                    b.Property<Guid>("MasterKategoriBayaranId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NamaKategoryBayaran")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("MasterKategoriBayaranId");

                    b.ToTable("MasterKategoriBayaran");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.MasterKategoriCaraPembayaran", b =>
                {
                    b.Property<Guid>("MasterKategoriCaraPembayaranId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaraPembayaran")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("MasterKategoriCaraPembayaranId");

                    b.ToTable("MasterKategoriCaraPembayaran");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.MasterKategoriPenjualan", b =>
                {
                    b.Property<Guid>("MasterKategoriPenjualanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NamaKategoryPenjualan")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("MasterKategoriPenjualanId");

                    b.ToTable("MasterKategoriPenjualan");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.MasterLeasing", b =>
                {
                    b.Property<Guid>("MasterLeasingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NamaLeasing")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("MasterLeasingId");

                    b.ToTable("MasterLeasing");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.MasterLeasingCabang", b =>
                {
                    b.Property<Guid>("MasterLeasingCabangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailCabang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("MasterLeasingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NamaCabang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("MasterLeasingCabangId");

                    b.HasIndex("MasterLeasingId");

                    b.ToTable("MasterLeasingCabang");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.PermohonanBPKB", b =>
                {
                    b.Property<Guid>("PermohonanBPKBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomorBpkb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PermohonanFakturId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TanggalTerimaBPKB")
                        .HasColumnType("datetime2");

                    b.HasKey("PermohonanBPKBId");

                    b.ToTable("PermohonanBPKB");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.PermohonanFaktur", b =>
                {
                    b.Property<Guid>("PermohonanFakturId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NamaFaktur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoRegistrasiFaktur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomorKTP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PenjualanDetailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("TanggalLahir")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TanggalMohonFaktur")
                        .HasColumnType("datetime2");

                    b.HasKey("PermohonanFakturId");

                    b.ToTable("PermohonanFaktur");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.PermohonanSTNK", b =>
                {
                    b.Property<Guid>("PermohonanSTNKId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BbnPabrik")
                        .HasColumnType("money");

                    b.Property<decimal>("BiayaTambahan")
                        .HasColumnType("money");

                    b.Property<decimal>("Birojasa")
                        .HasColumnType("money");

                    b.Property<decimal>("FormA")
                        .HasColumnType("money");

                    b.Property<string>("NoStnk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoUrutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomorPlat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PajakProgresif")
                        .HasColumnType("money");

                    b.Property<decimal>("PajakStnk")
                        .HasColumnType("money");

                    b.Property<int?>("PermohonanFakturDBId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Perwil")
                        .HasColumnType("money");

                    b.Property<int?>("ProgresifKe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TanggalBayarSTNK")
                        .HasColumnType("datetime2");

                    b.HasKey("PermohonanSTNKId");

                    b.ToTable("PermohonanSTNK");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.DataKonsumen", b =>
                {
                    b.OwnsOne("SumberMas2015.SalesMarketing.Domain.ValueObjects.Alamat", "AlamatKirim", b1 =>
                        {
                            b1.Property<Guid>("DataKonsumenId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Jalan")
                                .HasMaxLength(200)
                                .IsUnicode(false)
                                .HasColumnType("varchar(200)");

                            b1.Property<string>("Kecamatan")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Kelurahan")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("KodePos")
                                .HasMaxLength(7)
                                .HasColumnType("nvarchar(7)");

                            b1.Property<string>("Kota")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("NoFax")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("NoHandphone")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("NoTelepon")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Propinsi")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("DataKonsumenId");

                            b1.ToTable("DataKonsumen");

                            b1.WithOwner()
                                .HasForeignKey("DataKonsumenId");
                        });

                    b.OwnsOne("SumberMas2015.SalesMarketing.Domain.ValueObjects.Alamat", "AlamatTinggal", b1 =>
                        {
                            b1.Property<Guid>("DataKonsumenId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Jalan")
                                .HasMaxLength(200)
                                .IsUnicode(false)
                                .HasColumnType("varchar(200)");

                            b1.Property<string>("Kecamatan")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Kelurahan")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("KodePos")
                                .HasMaxLength(7)
                                .HasColumnType("nvarchar(7)");

                            b1.Property<string>("Kota")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("NoFax")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("NoHandphone")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("NoTelepon")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Propinsi")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("DataKonsumenId");

                            b1.ToTable("DataKonsumen");

                            b1.WithOwner()
                                .HasForeignKey("DataKonsumenId");
                        });

                    b.OwnsOne("SumberMas2015.SalesMarketing.Domain.ValueObjects.Name", "Nama", b1 =>
                        {
                            b1.Property<Guid>("DataKonsumenId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("NamaBelakang")
                                .IsRequired()
                                .IsUnicode(false)
                                .HasColumnType("varchar(max)");

                            b1.Property<string>("NamaDepan")
                                .IsRequired()
                                .IsUnicode(false)
                                .HasColumnType("varchar(max)");

                            b1.HasKey("DataKonsumenId");

                            b1.ToTable("DataKonsumen");

                            b1.WithOwner()
                                .HasForeignKey("DataKonsumenId");
                        });

                    b.OwnsOne("SumberMas2015.SalesMarketing.Domain.ValueObjects.Name", "NamaBPKB", b1 =>
                        {
                            b1.Property<Guid>("DataKonsumenId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("NamaBelakang")
                                .IsRequired()
                                .IsUnicode(false)
                                .HasColumnType("varchar(max)");

                            b1.Property<string>("NamaDepan")
                                .IsRequired()
                                .IsUnicode(false)
                                .HasColumnType("varchar(max)");

                            b1.HasKey("DataKonsumenId");

                            b1.ToTable("DataKonsumen");

                            b1.WithOwner()
                                .HasForeignKey("DataKonsumenId");
                        });

                    b.Navigation("AlamatKirim");

                    b.Navigation("AlamatTinggal");

                    b.Navigation("Nama");

                    b.Navigation("NamaBPKB");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.DataPenjualanDetail", b =>
                {
                    b.HasOne("SumberMas2015.SalesMarketing.Domain.DataPenjualan", null)
                        .WithMany("DataPenjualanDetails")
                        .HasForeignKey("DataPenjualanId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.DataSPKKredit", b =>
                {
                    b.HasOne("SumberMas2015.SalesMarketing.Domain.DataSPK", null)
                        .WithMany("DataSPKKredit")
                        .HasForeignKey("DataSPKId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.DataSPKLeasing", b =>
                {
                    b.HasOne("SumberMas2015.SalesMarketing.Domain.DataSPK", "DataSPK")
                        .WithMany("DataSPKLeasing")
                        .HasForeignKey("DataSPKId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SumberMas2015.SalesMarketing.Domain.MasterKategoriBayaran", "MasterKategoriBayaran")
                        .WithMany()
                        .HasForeignKey("MasterKategoriBayaranId");

                    b.HasOne("SumberMas2015.SalesMarketing.Domain.MasterKategoriPenjualan", "MasterKategoriPenjualan")
                        .WithMany()
                        .HasForeignKey("MasterKategoriPenjualanId");

                    b.HasOne("SumberMas2015.SalesMarketing.Domain.MasterLeasingCabang", "MasterLeasingCabang")
                        .WithMany()
                        .HasForeignKey("MasterLeasingCabangId");

                    b.Navigation("DataSPK");

                    b.Navigation("MasterKategoriBayaran");

                    b.Navigation("MasterKategoriPenjualan");

                    b.Navigation("MasterLeasingCabang");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.DataSPKSurvei", b =>
                {
                    b.HasOne("SumberMas2015.SalesMarketing.Domain.DataSPK", null)
                        .WithMany("DataSPKSurvei")
                        .HasForeignKey("DataSPKId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SumberMas2015.SalesMarketing.Domain.ValueObjects.Alamat", "AlamatPemesan", b1 =>
                        {
                            b1.Property<Guid>("DataSPKSurveiId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Jalan")
                                .HasMaxLength(200)
                                .IsUnicode(false)
                                .HasColumnType("varchar(200)");

                            b1.Property<string>("Kecamatan")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Kelurahan")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("KodePos")
                                .HasMaxLength(7)
                                .HasColumnType("nvarchar(7)");

                            b1.Property<string>("Kota")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("NoFax")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("NoHandphone")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("NoTelepon")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Propinsi")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("DataSPKSurveiId");

                            b1.ToTable("DataSPKSurvei");

                            b1.WithOwner()
                                .HasForeignKey("DataSPKSurveiId");
                        });

                    b.OwnsOne("SumberMas2015.SalesMarketing.Domain.ValueObjects.DataNPWP", "DataNPWPPemesan", b1 =>
                        {
                            b1.Property<Guid>("DataSPKSurveiId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("NamaNPWP")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("NoNPWP")
                                .HasMaxLength(25)
                                .HasColumnType("nvarchar(25)");

                            b1.HasKey("DataSPKSurveiId");

                            b1.ToTable("DataSPKSurvei");

                            b1.WithOwner()
                                .HasForeignKey("DataSPKSurveiId");

                            b1.OwnsOne("SumberMas2015.SalesMarketing.Domain.ValueObjects.Alamat", "AlamatNPWP", b2 =>
                                {
                                    b2.Property<Guid>("DataNPWPDataSPKSurveiId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Jalan")
                                        .HasMaxLength(200)
                                        .IsUnicode(false)
                                        .HasColumnType("varchar(200)");

                                    b2.Property<string>("Kecamatan")
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)");

                                    b2.Property<string>("Kelurahan")
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)");

                                    b2.Property<string>("KodePos")
                                        .HasMaxLength(7)
                                        .HasColumnType("nvarchar(7)");

                                    b2.Property<string>("Kota")
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)");

                                    b2.Property<string>("NoFax")
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)");

                                    b2.Property<string>("NoHandphone")
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)");

                                    b2.Property<string>("NoTelepon")
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)");

                                    b2.Property<string>("Propinsi")
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)");

                                    b2.HasKey("DataNPWPDataSPKSurveiId");

                                    b2.ToTable("DataSPKSurvei");

                                    b2.WithOwner()
                                        .HasForeignKey("DataNPWPDataSPKSurveiId");
                                });

                            b1.Navigation("AlamatNPWP");
                        });

                    b.OwnsOne("SumberMas2015.SalesMarketing.Domain.ValueObjects.Name", "NamaPemesan", b1 =>
                        {
                            b1.Property<Guid>("DataSPKSurveiId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("NamaBelakang")
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)");

                            b1.Property<string>("NamaDepan")
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)");

                            b1.HasKey("DataSPKSurveiId");

                            b1.ToTable("DataSPKSurvei");

                            b1.WithOwner()
                                .HasForeignKey("DataSPKSurveiId");
                        });

                    b.Navigation("AlamatPemesan");

                    b.Navigation("DataNPWPPemesan");

                    b.Navigation("NamaPemesan");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.MasterLeasingCabang", b =>
                {
                    b.HasOne("SumberMas2015.SalesMarketing.Domain.MasterLeasing", null)
                        .WithMany("MasterLeasingCabangs")
                        .HasForeignKey("MasterLeasingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SumberMas2015.SalesMarketing.Domain.ValueObjects.Alamat", "AlamatCabangLeasing", b1 =>
                        {
                            b1.Property<Guid>("MasterLeasingCabangId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Jalan")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("Kecamatan")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Kelurahan")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("KodePos")
                                .HasMaxLength(7)
                                .HasColumnType("nvarchar(7)");

                            b1.Property<string>("Kota")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("NoFax")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("NoHandphone")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("NoTelepon")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Propinsi")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("MasterLeasingCabangId");

                            b1.ToTable("MasterLeasingCabang");

                            b1.WithOwner()
                                .HasForeignKey("MasterLeasingCabangId");
                        });

                    b.Navigation("AlamatCabangLeasing");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.PermohonanFaktur", b =>
                {
                    b.OwnsOne("SumberMas2015.SalesMarketing.Domain.ValueObjects.Alamat", "AlamatFaktur", b1 =>
                        {
                            b1.Property<Guid>("PermohonanFakturId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Jalan")
                                .HasMaxLength(200)
                                .IsUnicode(false)
                                .HasColumnType("varchar(200)");

                            b1.Property<string>("Kecamatan")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Kelurahan")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("KodePos")
                                .HasMaxLength(7)
                                .HasColumnType("nvarchar(7)");

                            b1.Property<string>("Kota")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("NoFax")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("NoHandphone")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("NoTelepon")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Propinsi")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("PermohonanFakturId");

                            b1.ToTable("PermohonanFaktur");

                            b1.WithOwner()
                                .HasForeignKey("PermohonanFakturId");
                        });

                    b.Navigation("AlamatFaktur");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.DataPenjualan", b =>
                {
                    b.Navigation("DataPenjualanDetails");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.DataSPK", b =>
                {
                    b.Navigation("DataSPKKredit");

                    b.Navigation("DataSPKLeasing");

                    b.Navigation("DataSPKSurvei");
                });

            modelBuilder.Entity("SumberMas2015.SalesMarketing.Domain.MasterLeasing", b =>
                {
                    b.Navigation("MasterLeasingCabangs");
                });
#pragma warning restore 612, 618
        }
    }
}
