// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmmCoreDDD2019.Persistence;

namespace SmmCoreDDD2019.Persistence.Migrations.SqlServerMigrations
{
    [DbContext(typeof(SMMCoreDDD2019DbContext))]
    [Migration("20190126105636_InitialCreate2")]
    partial class InitialCreate2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.CustomerDB", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CustomerID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alamat")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("AlamatKirim")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("Faks")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Handphone")
                        .HasMaxLength(20);

                    b.Property<string>("Jual")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Kecamatan")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("Kelurahan")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("KodePos")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Kota")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Nama")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("NamaBPKB")
                        .HasColumnName("NamaBPKB")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("NoKtp")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Pekerjaan")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Propinsi")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Telp")
                        .HasMaxLength(20);

                    b.Property<string>("TelpKantor")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("TglInput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("TglLahir")
                        .HasColumnType("datetime");

                    b.Property<int?>("UserIDPeg")
                        .HasColumnName("UserIDPeg");

                    b.Property<string>("UserInput")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("CustomerID");

                    b.ToTable("CustomerDB");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataPegawai", b =>
                {
                    b.Property<int>("IDPegawai")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDPegawai")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aktif")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<DateTime?>("TglBerhentiKerja")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("TglInput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("TglMulaiKerja")
                        .HasColumnType("datetime");

                    b.HasKey("IDPegawai");

                    b.ToTable("DataPegawai","DataPegawai");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataPegawaiDataJabatan", b =>
                {
                    b.Property<int>("NoUrut")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IDPegawai");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(400)
                        .IsUnicode(false);

                    b.Property<int?>("NoUrutJabatan")
                        .HasColumnName("NoUrutJabatan");

                    b.Property<DateTime?>("TglBerhentiMenjabat")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("TglMenjabat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("NoUrut");

                    b.HasIndex("NoUrutJabatan");

                    b.ToTable("DataPegawaiDataJabatan","DataPegawai");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataPegawaiDataKeluarga", b =>
                {
                    b.Property<int>("NoUrut")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Agama")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("AlamatK")
                        .HasColumnName("alamatK")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("EmergencyCall")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Handphone")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("HubunganK")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<int?>("IDPegawai")
                        .HasColumnName("IDPegawai");

                    b.Property<string>("JenisKelamin")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("KecamatanK")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("KelurahanK")
                        .HasColumnName("kelurahanK")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Keterangan")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("KodePosK")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("KotaK")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("NamaK")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("NoKtp")
                        .HasColumnName("NoKTP")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Pekerjaan")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("PendidikanTerakhir")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("PropinsiK")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Telp")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("TempatLahir")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("TglInput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("Tgllahir")
                        .HasColumnName("Tgllahir")
                        .HasColumnType("datetime");

                    b.HasKey("NoUrut");

                    b.HasIndex("IDPegawai");

                    b.ToTable("DataPegawaiDataKeluarga","DataPegawai");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataPegawaiDataOrmas", b =>
                {
                    b.Property<int>("NoUrut")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlamatOrmas")
                        .HasColumnName("AlamatOrmas")
                        .HasMaxLength(300)
                        .IsUnicode(false);

                    b.Property<int?>("IDPegawai")
                        .HasColumnName("IDPegawai");

                    b.Property<string>("Jabatan")
                        .HasColumnName("Jabatan")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("JenisKegiatan")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("KotaOrmas")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("NamaOrmas")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("TelpOrmas")
                        .HasColumnName("TelpOrmas")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("TglInput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("NoUrut");

                    b.HasIndex("IDPegawai");

                    b.ToTable("DataPegawaiDataOrmas","DataPegawai");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataPegawaiDataPribadi", b =>
                {
                    b.Property<int>("NoUrut")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Agama")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("AlamatKTP")
                        .HasColumnName("AlamatKTP")
                        .HasMaxLength(300)
                        .IsUnicode(false);

                    b.Property<string>("AlamatRumah")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("GolonganDarah")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("Handphone")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Handphone2")
                        .HasColumnName("Handphone2")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<int?>("IDPegawai")
                        .HasColumnName("IDPegawai");

                    b.Property<string>("JenisKelamin")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("KecamatanKTP")
                        .HasColumnName("KecamatanKTP")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("KecamatanRumah")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("KelurahanKTP")
                        .HasColumnName("KelurahanKTP")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("KelurahanRumah")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("KodePos")
                        .HasColumnName("KodePos")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("KodePosKTP")
                        .HasColumnName("KodePosKTP")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("KotaKTP")
                        .HasColumnName("KotaKTP")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("KotaRumah")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("NamaBelakang")
                        .HasMaxLength(75)
                        .IsUnicode(false);

                    b.Property<string>("NamaDepan")
                        .HasMaxLength(75)
                        .IsUnicode(false);

                    b.Property<string>("NamaTengah")
                        .HasMaxLength(75)
                        .IsUnicode(false);

                    b.Property<string>("NoKTP")
                        .HasColumnName("NoKTP")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("PropinsiKTP")
                        .HasColumnName("PropinsiKTP")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("PropinsiRumah")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("StatusKawin")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("StatusTempatTinggal")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<DateTime?>("TanggalLahir")
                        .HasColumnType("datetime");

                    b.Property<string>("Telp")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("TempatLahir")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<DateTime?>("TglInput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("NoUrut");

                    b.HasIndex("IDPegawai")
                        .IsUnique()
                        .HasFilter("[IDPegawai] IS NOT NULL");

                    b.ToTable("DataPegawaiDataPribadi","DataPegawai");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataPegawaiDataRiwayatPekerjaan", b =>
                {
                    b.Property<int>("NoUrut")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AkhirBekerja")
                        .HasColumnType("datetime");

                    b.Property<string>("AlamatP")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("AtasanP")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<decimal?>("GajiTerakhir")
                        .HasColumnType("money");

                    b.Property<int?>("IDPegawai")
                        .HasColumnName("IDPegawai");

                    b.Property<string>("JabatanAkhir")
                        .HasColumnName("JabatanAkhir")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("JabatanAwal")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("KecamatanP")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("KelurahanP")
                        .HasColumnName("KelurahanP")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Keterangan")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("KodePosP")
                        .HasMaxLength(7)
                        .IsUnicode(false);

                    b.Property<string>("KotaP")
                        .HasColumnName("KotaP")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("MulaiBekerja")
                        .HasColumnType("datetime");

                    b.Property<string>("NamaPerusahaan")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("PropinsiP")
                        .HasColumnName("PropinsiP")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("TelpP")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("TglInput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("NoUrut");

                    b.HasIndex("IDPegawai");

                    b.ToTable("DataPegawaiDataRiwayatPekerjaan","DataPegawai");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataPegawaiDataRiwayatPelatihan", b =>
                {
                    b.Property<int>("NoUrut")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlamatLembaga")
                        .HasColumnName("AlamatLembaga")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("BidangPelatihan")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("DibiayaiOleh")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int?>("IDPegawai")
                        .HasColumnName("IDPegawai");

                    b.Property<string>("LamaKursus")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("NamaLembaga")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("TelpLembaga")
                        .HasColumnName("TelpLembaga")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("NoUrut");

                    b.HasIndex("IDPegawai");

                    b.ToTable("DataPegawaiDataRiwayatPelatihan","DataPegawai");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataPegawaiDataRiwayatPendidikan", b =>
                {
                    b.Property<int>("NoUrut")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IDPegawai")
                        .HasColumnName("IDPegawai");

                    b.Property<string>("Jurusan")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Keterangan")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Kota")
                        .HasColumnName("Kota")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("NamaSekolah")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int?>("TahunLulus");

                    b.Property<string>("TingkatPend")
                        .HasColumnType("nchar(10)");

                    b.HasKey("NoUrut");

                    b.HasIndex("IDPegawai");

                    b.ToTable("DataPegawaiDataRiwayatPendidikan","DataPegawai");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataPegawaiFoto", b =>
                {
                    b.Property<int>("NoUrut")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Foto")
                        .HasColumnType("image");

                    b.Property<int?>("IDPegawai")
                        .HasColumnName("IDPegawai");

                    b.Property<string>("KodeBarcode")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<string>("Revisi")
                        .HasColumnName("revisi")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Tglinput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("NoUrut");

                    b.HasIndex("IDPegawai");

                    b.ToTable("DataPegawaiFoto","DataPegawai");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataPerusahaan", b =>
                {
                    b.Property<int>("KodeP")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlamatP")
                        .HasMaxLength(50);

                    b.Property<string>("Cs")
                        .HasColumnName("CS")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("Kec")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Kel")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("KodePos")
                        .HasMaxLength(7)
                        .IsUnicode(false);

                    b.Property<string>("Kota")
                        .HasMaxLength(50);

                    b.Property<string>("NamaP")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Propinsi")
                        .HasMaxLength(50);

                    b.Property<string>("Telp")
                        .HasMaxLength(25);

                    b.HasKey("KodeP");

                    b.ToTable("DataPerusahaan","DataPerusahaan");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataPerusahaanCabang", b =>
                {
                    b.Property<int>("KodePosisi")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alamat")
                        .HasColumnName("Alamat")
                        .HasMaxLength(50);

                    b.Property<string>("Cp")
                        .HasColumnName("CP")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Kec")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Kel")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("KodeP");

                    b.Property<string>("KodePos")
                        .HasMaxLength(7)
                        .IsUnicode(false);

                    b.Property<string>("Kota")
                        .HasMaxLength(50);

                    b.Property<string>("NamaPosisi")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Propinsi")
                        .HasMaxLength(50);

                    b.Property<string>("Telp")
                        .HasColumnName("Telp")
                        .HasMaxLength(20);

                    b.HasKey("KodePosisi");

                    b.HasIndex("KodeP");

                    b.ToTable("DataPerusahaanCabang","DataPerusahaan");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataSPKBaruDB", b =>
                {
                    b.Property<int>("NoUrutSPKBaru")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LokasiSpk")
                        .HasColumnName("LokasiSpk")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Terinput")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<DateTime?>("TglInput")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Tolak")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<int?>("UserIdpeg");

                    b.Property<string>("UserInput")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("NoUrutSPKBaru");

                    b.ToTable("DataSPKBaruDB","DataSPKBaruDB");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataSPKKendaraanDB", b =>
                {
                    b.Property<int>("NoUrut")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NamaSTNK")
                        .HasColumnName("NamaSTNK")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("NoKtpSTNK")
                        .HasColumnName("NoKtpSTNK")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int?>("NoUrutSPKBaru")
                        .HasColumnName("NoUrutSPKBaru");

                    b.Property<int?>("NoUrutTypeKendaraan")
                        .HasColumnName("NoUrutTypeKendaraan");

                    b.Property<string>("TahunPerakitan")
                        .HasColumnName("tahunPerakitan")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("Warna")
                        .HasMaxLength(35)
                        .IsUnicode(false);

                    b.HasKey("NoUrut");

                    b.HasIndex("NoUrutSPKBaru");

                    b.ToTable("DataSPKKendaraanDB","DataSPKBaruDB");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataSPKKreditDB", b =>
                {
                    b.Property<int>("NoUrut")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("BBN")
                        .HasColumnName("BBN")
                        .HasColumnType("money");

                    b.Property<decimal?>("BiayaAdministrasiKredit")
                        .HasColumnType("money");

                    b.Property<decimal?>("BiayaAdministrasiTunai")
                        .HasColumnType("money");

                    b.Property<decimal?>("DPPriceList")
                        .HasColumnName("DPPricelist")
                        .HasColumnType("money");

                    b.Property<decimal?>("DendaWilayah")
                        .HasColumnType("money");

                    b.Property<decimal?>("DiskonDP")
                        .HasColumnName("DiskonDP")
                        .HasColumnType("money");

                    b.Property<decimal?>("DiskonTunai")
                        .HasColumnType("money");

                    b.Property<decimal?>("Komisi")
                        .HasColumnType("money");

                    b.Property<int?>("NoUrutSPKBaru")
                        .HasColumnName("NourutSPKBaru");

                    b.Property<decimal?>("OffTheRoad")
                        .HasColumnType("money");

                    b.Property<decimal?>("Promosi")
                        .HasColumnType("money");

                    b.Property<decimal?>("UangTandaJadiKredit")
                        .HasColumnType("money");

                    b.Property<decimal?>("UangTandaJadiTunai")
                        .HasColumnType("money");

                    b.HasKey("NoUrut");

                    b.HasIndex("NoUrutSPKBaru");

                    b.ToTable("DataSPKKreditDB","DataSPKBaruDB");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataSPKLeasingDB", b =>
                {
                    b.Property<int>("NoUrut")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Angsuran")
                        .HasColumnType("money");

                    b.Property<string>("Mediator")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("NamaCmo")
                        .HasColumnName("NamaCMO")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int?>("NoUrutKategoriBayaran");

                    b.Property<int?>("NoUrutKategoriPenjualan")
                        .HasColumnName("NoUrutKategoriPenjualan");

                    b.Property<int?>("NoUrutLeasingCabang")
                        .HasColumnName("NoUrutLeasingCabang");

                    b.Property<int?>("NoUrutSPKBaru")
                        .HasColumnName("NoUrutSPKBaru");

                    b.Property<int?>("NoUrutSales");

                    b.Property<int?>("Tenor")
                        .HasColumnName("tenor");

                    b.Property<DateTime?>("TglSurvei")
                        .HasColumnType("datetime");

                    b.HasKey("NoUrut");

                    b.HasIndex("NoUrutKategoriBayaran");

                    b.HasIndex("NoUrutKategoriPenjualan");

                    b.HasIndex("NoUrutLeasingCabang");

                    b.HasIndex("NoUrutSPKBaru");

                    b.ToTable("DataSPKLeasingDB","DataSPKBaruDB");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataSPKSurveiDB", b =>
                {
                    b.Property<int>("NoUrut")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlamatPemesan")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<string>("HandphonePemesan")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("KecamatanPemesan")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("KelurahanPemesan")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("KodePosPemesan")
                        .HasMaxLength(7)
                        .IsUnicode(false);

                    b.Property<string>("KotaPemesan")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("NamaNPWP")
                        .HasColumnName("NamaNPWP")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("NamaPemesan")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("NoKtpPemesan")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<string>("NoNPWP")
                        .HasColumnName("NoNPWP")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int?>("NoUrutSPKBaru")
                        .HasColumnName("NoUrutSPKBaru");

                    b.Property<string>("PekerjaanPemesan")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("PropinsiPemesan")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("TelpPemesan")
                        .HasMaxLength(18)
                        .IsUnicode(false);

                    b.HasKey("NoUrut");

                    b.HasIndex("NoUrutSPKBaru");

                    b.ToTable("DataSPKSurveiDB","DataSPKBaruDB");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.MasterBarangDB", b =>
                {
                    b.Property<int>("NoUrutTypeKendaraan")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("NoUrutTypeKendaraan")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aktif")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<decimal?>("BBN")
                        .HasColumnName("BBN")
                        .HasColumnType("money");

                    b.Property<string>("Cc")
                        .HasColumnName("CC")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<decimal?>("Harga")
                        .HasColumnType("money");

                    b.Property<string>("Merek")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<string>("NamaBarang")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("NomorMesin")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("NomorRangka")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<int?>("Tahun");

                    b.Property<string>("Tipe")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("TypeKendaraan")
                        .IsRequired()
                        .HasColumnName("TypeKendaraan")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("NoUrutTypeKendaraan");

                    b.ToTable("MasterBarangDB");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.MasterJenisJabatan", b =>
                {
                    b.Property<int>("NoUrut")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NamaJabatan")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("NoUrut");

                    b.ToTable("MasterJenisJabatan");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.MasterKategoriBayaran", b =>
                {
                    b.Property<int>("NoUrut")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NamaKategoryBayaran")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("NoUrut");

                    b.ToTable("MasterKategoriBayaran");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.MasterKategoriCaraPembayaran", b =>
                {
                    b.Property<int>("NoUrutCaraBayar")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CaraPembayaran")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("NoUrutCaraBayar");

                    b.ToTable("MasterKategoriCaraPembayaran");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.MasterKategoriPenjualan", b =>
                {
                    b.Property<int>("NoUrutKategoriPenjualan")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NamaKategoryPenjualan")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("NoUrutKategoriPenjualan");

                    b.ToTable("MasterKategoriPenjualan");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.MasterLeasingCabangDB", b =>
                {
                    b.Property<int>("NoUrutLeasingCabang")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aktif")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Alamat")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Cabang")
                        .HasColumnName("Cabang")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Faks")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<int>("IDlease")
                        .HasColumnName("IDlease");

                    b.Property<string>("Kecamatan")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Kelurahan")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("KodePos")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Kota")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Propinsi")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Telp")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("NoUrutLeasingCabang");

                    b.HasIndex("IDlease");

                    b.ToTable("MasterLeasingCabangDB","MasterLeasingDb");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.MasterLeasingDb", b =>
                {
                    b.Property<int>("IDlease")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDlease")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NamaLease")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("IDlease");

                    b.ToTable("MasterLeasingDB","MasterLeasingDB");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.MasterSupplierDB", b =>
                {
                    b.Property<int>("IDSupplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDSupplier")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aktif")
                        .HasMaxLength(2);

                    b.Property<string>("Alamat")
                        .HasMaxLength(100);

                    b.Property<string>("Email")
                        .HasMaxLength(30);

                    b.Property<string>("Faks")
                        .HasMaxLength(20);

                    b.Property<string>("Kecamatan")
                        .HasMaxLength(50);

                    b.Property<string>("Kelurahan")
                        .HasMaxLength(50);

                    b.Property<string>("KodePos")
                        .HasMaxLength(10);

                    b.Property<string>("Kota")
                        .HasMaxLength(50);

                    b.Property<string>("NamaSupplier")
                        .IsRequired()
                        .HasColumnName("NamaSupplier")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Propinsi")
                        .HasMaxLength(50);

                    b.Property<string>("Telp")
                        .HasMaxLength(20);

                    b.HasKey("IDSupplier");

                    b.ToTable("MasterSupplierDB");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.Pembelian", b =>
                {
                    b.Property<int>("KodeBeli")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Batal")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<int?>("Idsupplier")
                        .HasColumnName("IDSupplier");

                    b.Property<string>("JenisTransPmb")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Keterangan")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<string>("Kredit")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<int?>("NoPOPembelian")
                        .HasColumnName("NoPOPembelian");

                    b.Property<DateTime?>("TglBeli")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserInput")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int?>("UserInputId")
                        .HasColumnName("UserInputId");

                    b.HasKey("KodeBeli");

                    b.ToTable("Pembelian","Pembelian");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.PembelianDetail", b =>
                {
                    b.Property<int>("KodeBeliDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("KodeBeliDetail")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("BBN")
                        .HasColumnName("BBN")
                        .HasColumnType("money");

                    b.Property<decimal?>("Diskon")
                        .HasColumnName("Diskon")
                        .HasColumnType("money");

                    b.Property<decimal?>("Diskon2")
                        .HasColumnName("Diskon2")
                        .HasColumnType("money");

                    b.Property<decimal?>("DiskonPPN")
                        .HasColumnName("DiskonPPN")
                        .HasColumnType("money");

                    b.Property<decimal?>("Harga1")
                        .HasColumnName("Harga1")
                        .HasColumnType("money");

                    b.Property<decimal?>("HargaOffTheRoad")
                        .HasColumnType("money");

                    b.Property<decimal?>("HargaPPN")
                        .HasColumnName("HargaPPN")
                        .HasColumnType("money");

                    b.Property<int>("KodeBeli")
                        .HasColumnName("KodeBeli");

                    b.Property<int?>("KodeBrg")
                        .HasColumnName("KodeBrg");

                    b.Property<int>("Qty")
                        .HasColumnName("Qty");

                    b.Property<decimal?>("SellIn")
                        .HasColumnName("SellIn")
                        .HasColumnType("money");

                    b.Property<decimal?>("SellIn2")
                        .HasColumnName("SellIn2")
                        .HasColumnType("money");

                    b.Property<decimal?>("SellInPPN")
                        .HasColumnName("SellInPPN")
                        .HasColumnType("money");

                    b.HasKey("KodeBeliDetail");

                    b.ToTable("PembelianDetail","Pembelian");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.PembelianPO", b =>
                {
                    b.Property<int>("NoUrutPo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("NoUrutPo")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Keterangan")
                        .HasMaxLength(300)
                        .IsUnicode(false);

                    b.Property<int?>("NoDealer")
                        .HasColumnName("NoDealer");

                    b.Property<string>("PoAstra")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<string>("Terinput")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<DateTime?>("TglPo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TglPo")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UserId")
                        .HasColumnName("UserId");

                    b.Property<string>("UserInput")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("NoUrutPo");

                    b.ToTable("PembelianPO","PembelianPO");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.PembelianPODetail", b =>
                {
                    b.Property<int>("NoUrutPoDet")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Bbn")
                        .HasColumnName("BBn")
                        .HasColumnType("money");

                    b.Property<decimal?>("Diskon")
                        .HasColumnType("money");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<int?>("NoUrutMasterBarang")
                        .HasColumnName("NoUrutMasterBarang");

                    b.Property<int?>("NoUrutPo")
                        .HasColumnName("NoUrutPO");

                    b.Property<decimal?>("OffTheRoad")
                        .HasColumnType("money");

                    b.Property<int?>("Qty")
                        .HasColumnName("Qty");

                    b.Property<string>("Warna")
                        .HasColumnName("Warna")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.HasKey("NoUrutPoDet");

                    b.ToTable("PembelianPODetail","PembelianPO");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.Penjualan", b =>
                {
                    b.Property<int>("KodePenjualan")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Batal")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<int?>("KategoriPenjualan")
                        .HasColumnName("KategoriPenjualan");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(300)
                        .IsUnicode(false);

                    b.Property<int?>("KodeKonsumen")
                        .HasColumnName("KodeKonsumen");

                    b.Property<int?>("KodeLease")
                        .HasColumnName("KodeLease");

                    b.Property<string>("Mediator")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("NoBuku")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<int?>("NoUrutSPK")
                        .HasColumnName("NoUrutSPK");

                    b.Property<int?>("NoUrutSales")
                        .HasColumnName("NoUrutSales");

                    b.Property<DateTime?>("TanggalPenjualan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UserInput")
                        .HasColumnName("USerInput")
                        .HasMaxLength(20);

                    b.Property<int?>("UserInputId")
                        .HasColumnName("UserInputID");

                    b.HasKey("KodePenjualan");

                    b.ToTable("Penjualan","Penjualan");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.PenjualanDetail", b =>
                {
                    b.Property<int>("NoPenjualanDetail")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("BBN")
                        .HasColumnName("BBN")
                        .HasColumnType("money");

                    b.Property<string>("CheckDp")
                        .HasColumnName("CheckDP")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<decimal?>("DendaWilayah")
                        .HasColumnType("money");

                    b.Property<decimal?>("DiskonKredit")
                        .HasColumnType("money");

                    b.Property<decimal?>("DiskonTunai")
                        .HasColumnType("money");

                    b.Property<decimal?>("HargaOTR")
                        .HasColumnName("HargaOTR")
                        .HasColumnType("money");

                    b.Property<decimal?>("JoinPromo1")
                        .HasColumnType("money");

                    b.Property<decimal?>("JoinPromo2")
                        .HasColumnType("money");

                    b.Property<int?>("KodePenjualan")
                        .HasColumnName("KodePenjualan");

                    b.Property<decimal?>("Komisi")
                        .HasColumnType("money");

                    b.Property<int?>("NoUrutSO")
                        .HasColumnName("NoUrutSO");

                    b.Property<decimal?>("OffTheRoad")
                        .HasColumnName("OffTheRoad")
                        .HasColumnType("money");

                    b.Property<decimal?>("Promosi")
                        .HasColumnType("money");

                    b.Property<decimal?>("SPF")
                        .HasColumnName("SPF")
                        .HasColumnType("money");

                    b.Property<decimal?>("SellOut")
                        .HasColumnType("money");

                    b.Property<decimal?>("Subsidi")
                        .HasColumnType("money");

                    b.Property<decimal?>("UangMuka")
                        .HasColumnType("money");

                    b.HasKey("NoPenjualanDetail");

                    b.ToTable("PenjualanDetail","Penjualan");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.PermohonanFakturDB", b =>
                {
                    b.Property<int>("NoUrutFaktur")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alamat")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<string>("HandphoneF")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Kecamatan")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.Property<string>("Kelurahan")
                        .HasColumnName("kelF")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.Property<int?>("KodePenjualanDetail")
                        .HasColumnName("KodePenjualanDetail");

                    b.Property<string>("KodePos")
                        .HasMaxLength(7)
                        .IsUnicode(false);

                    b.Property<string>("Kota")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.Property<string>("NamaFaktur")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("NomorKTP")
                        .HasColumnName("NomorKTP")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Propinsi")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.Property<DateTime?>("TanggalLahir")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("TanggalMohonFaktur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Telepon")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.HasKey("NoUrutFaktur");

                    b.ToTable("PermohonanFakturDB","Penjualan");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.StokUnit", b =>
                {
                    b.Property<int>("NoUrutSo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Diskon")
                        .HasColumnName("Diskon")
                        .HasColumnType("money");

                    b.Property<decimal?>("Diskon2")
                        .HasColumnName("Diskon2")
                        .HasColumnType("money");

                    b.Property<decimal?>("DiskonPPN")
                        .HasColumnName("DiskonPPN")
                        .HasColumnType("money");

                    b.Property<string>("Faktur")
                        .HasColumnName("Faktur")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<decimal?>("Harga")
                        .HasColumnName("Harga")
                        .HasColumnType("money");

                    b.Property<decimal?>("Harga1")
                        .HasColumnName("Harga1")
                        .HasColumnType("money");

                    b.Property<decimal?>("HargaPPN")
                        .HasColumnName("HargaPPN")
                        .HasColumnType("money");

                    b.Property<string>("Jual")
                        .HasColumnName("Jual")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Kembali")
                        .HasColumnName("Kembali")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<int?>("KodeBeli")
                        .HasColumnName("KodeBeli");

                    b.Property<int?>("KodeBrg")
                        .HasColumnName("KodeBrg");

                    b.Property<string>("NoMesin")
                        .HasColumnName("NoMesin")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("NoRangka")
                        .HasColumnName("NoRangka")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<decimal?>("SellIn")
                        .HasColumnName("SellIn")
                        .HasColumnType("money");

                    b.Property<decimal?>("SellIn2")
                        .HasColumnName("SellIn2")
                        .HasColumnType("money");

                    b.Property<decimal?>("SellInPPN")
                        .HasColumnName("SellInPPN")
                        .HasColumnType("money");

                    b.Property<DateTime?>("TglInput")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TglInput")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Warna")
                        .HasColumnName("Warna")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.HasKey("NoUrutSo");

                    b.ToTable("StokUnit","Pembelian");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataPegawaiDataJabatan", b =>
                {
                    b.HasOne("SmmCoreDDD2019.Domain.Entities.MasterJenisJabatan", "MasterJenisJabatan")
                        .WithMany("DataPegawaiDataJabatan")
                        .HasForeignKey("NoUrutJabatan")
                        .HasConstraintName("FK_DataPegawaiDataJabatan_MasterJenisJabatan");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataPegawaiDataKeluarga", b =>
                {
                    b.HasOne("SmmCoreDDD2019.Domain.Entities.DataPegawai", "DataPegawai")
                        .WithMany("DataPegawaiDataKeluarga")
                        .HasForeignKey("IDPegawai")
                        .HasConstraintName("FK_DataPegawaiDataKeluarga_DataPegawai");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataPegawaiDataOrmas", b =>
                {
                    b.HasOne("SmmCoreDDD2019.Domain.Entities.DataPegawai", "DataPegawai")
                        .WithMany("DataPegawaiDataOrmas")
                        .HasForeignKey("IDPegawai")
                        .HasConstraintName("FK_DataPegawaiDataOrmas_DataPegawai");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataPegawaiDataPribadi", b =>
                {
                    b.HasOne("SmmCoreDDD2019.Domain.Entities.DataPegawai", "DataPegawai")
                        .WithOne("DataPegawaiDataPribadi")
                        .HasForeignKey("SmmCoreDDD2019.Domain.Entities.DataPegawaiDataPribadi", "IDPegawai")
                        .HasConstraintName("FK_DataPegawaiDataPribadi_DataPegawai");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataPegawaiDataRiwayatPekerjaan", b =>
                {
                    b.HasOne("SmmCoreDDD2019.Domain.Entities.DataPegawai", "DataPegawai")
                        .WithMany("DataPegawaiDataRiwayatPekerjaan")
                        .HasForeignKey("IDPegawai")
                        .HasConstraintName("FK_DataPegawaiDataRiwayatPekerjaan_DataPegawai");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataPegawaiDataRiwayatPelatihan", b =>
                {
                    b.HasOne("SmmCoreDDD2019.Domain.Entities.DataPegawai", "DataPegawai")
                        .WithMany("DataPegawaiDataRiwayatPelatihan")
                        .HasForeignKey("IDPegawai")
                        .HasConstraintName("FK_DataPegawaiDataRiwayatPelatihan_DataPegawai");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataPegawaiDataRiwayatPendidikan", b =>
                {
                    b.HasOne("SmmCoreDDD2019.Domain.Entities.DataPegawai", "DataPegawai")
                        .WithMany("DataPegawaiDataRiwayatPendidikan")
                        .HasForeignKey("IDPegawai")
                        .HasConstraintName("FK_DataPegawaiDataRiwayatPendidikan_DataPegawai");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataPegawaiFoto", b =>
                {
                    b.HasOne("SmmCoreDDD2019.Domain.Entities.DataPegawai", "DataPegawai")
                        .WithMany("DataPegawaiFoto")
                        .HasForeignKey("IDPegawai")
                        .HasConstraintName("FK_DataPegawaiFoto_DataPegawai");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataPerusahaanCabang", b =>
                {
                    b.HasOne("SmmCoreDDD2019.Domain.Entities.DataPerusahaan", "DataPerusahaan")
                        .WithMany("DataPerusahaanCabang")
                        .HasForeignKey("KodeP")
                        .HasConstraintName("FK_DataPerusahaanCabang_DataPerusahaan");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataSPKKendaraanDB", b =>
                {
                    b.HasOne("SmmCoreDDD2019.Domain.Entities.DataSPKBaruDB", "DataSPKBaruDB")
                        .WithMany("DataSPKKendaraanDB")
                        .HasForeignKey("NoUrutSPKBaru")
                        .HasConstraintName("FK_DataSPKKendaraanDB_DataSPKBaruDB");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataSPKKreditDB", b =>
                {
                    b.HasOne("SmmCoreDDD2019.Domain.Entities.DataSPKBaruDB", "DataSPKBaruDB")
                        .WithMany("DataSPKKreditDB")
                        .HasForeignKey("NoUrutSPKBaru")
                        .HasConstraintName("FK_DataSPKKreditDB_DataSPKBaruDB");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataSPKLeasingDB", b =>
                {
                    b.HasOne("SmmCoreDDD2019.Domain.Entities.MasterKategoriBayaran", "MasterKategoriBayaran")
                        .WithMany("DataSPKLeasingDB")
                        .HasForeignKey("NoUrutKategoriBayaran")
                        .HasConstraintName("FK_DataSPKLeasingDB_MasterKategoriBayaran");

                    b.HasOne("SmmCoreDDD2019.Domain.Entities.MasterKategoriPenjualan", "MasterKategoriPenjualan")
                        .WithMany("DataSPKLeasingDB")
                        .HasForeignKey("NoUrutKategoriPenjualan")
                        .HasConstraintName("FK_DataSPKLeasingDB_MasterKategoriPenjualan");

                    b.HasOne("SmmCoreDDD2019.Domain.Entities.MasterLeasingCabangDB", "MasterLeasingCabangDB")
                        .WithMany("DataSPKLeasingDB")
                        .HasForeignKey("NoUrutLeasingCabang")
                        .HasConstraintName("FK_DataSPKLeasingDB_MasterLeasingDb");

                    b.HasOne("SmmCoreDDD2019.Domain.Entities.DataSPKBaruDB", "DataSPKBaruDB")
                        .WithMany("DataSPKLeasingDB")
                        .HasForeignKey("NoUrutSPKBaru")
                        .HasConstraintName("FK_DataSPKLeasingDB_DataSPKBaruDB");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.DataSPKSurveiDB", b =>
                {
                    b.HasOne("SmmCoreDDD2019.Domain.Entities.DataSPKBaruDB", "DataSPKBaruDB")
                        .WithMany("DataSPKSurveiDB")
                        .HasForeignKey("NoUrutSPKBaru")
                        .HasConstraintName("FK_DataSPKSurveiDB_DataSPKBaruDB");
                });

            modelBuilder.Entity("SmmCoreDDD2019.Domain.Entities.MasterLeasingCabangDB", b =>
                {
                    b.HasOne("SmmCoreDDD2019.Domain.Entities.MasterLeasingDb", "MasterLeasingDb")
                        .WithMany("MasterLeasingCabangDB")
                        .HasForeignKey("IDlease")
                        .HasConstraintName("FK_MasterLeasingCabangDB_MasterLeasingDb");
                });
#pragma warning restore 612, 618
        }
    }
}
